In [1]:
# Import necessary modules.
import os
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
# Check current working dir.
os.getcwd()

'c:\\Users\\Hosig Lee\\PythonPrjs\\Exercise_Energy_Data_Analysis'

In [3]:
# Set working dir to main working dir.
# os.chdir("c:\\PythonProject\\EDA-Project")
# os.getcwd()

In [4]:
# Raw data file path
str_raw_data_path = "./data/rawData/sKor_raw_data_2017_v02.xlsx"

In [5]:
# Import raw data for household characters from excel file
df_raw_hh = pd.read_excel(str_raw_data_path, sheet_name= "household")

In [6]:
# Check raw dataframe.
df_raw_hh.head(10)

id_hs       id_hh  cat_loc_div  cat_sz_cty  cat_hus_typ  num_flr  \
0  HS1101000001  HH13110253           11           1            3        9   
1  HS1101000002  HH14110053           11           1            2        2   
2  HS1101000004  HH14110055           11           1            2        1   
3  HS1101000005  HH13110254           11           1            1        2   
4  HS1101000007  HH14110057           11           1            1        1   
5  HS1101000008  HH14110058           11           1            1        2   
6  HS1101000009  HH17110001           11           1            1        1   
7  HS1101000010  HH14110056           11           1            1        1   
8  HS1102000001  HH13110255           11           1            2        2   
9  HS1102000003  HH11110023           11           1            1        1   

   num_out_wls  cat_hus_dir_fce  cat_hus_blt_yr  num_hus_ar  ...  num_liv  \
0            4                3               5          38  ...        1   
1            4                1               5          30  ...        1   
2            6                1               3          48  ...        1   
3            4                5               3          80  ...        2   
4            5                5               3          19  ...        1   
5            5                3               3          35  ...        1   
6            4                5               6          40  ...        1   
7            6                3               6          45  ...        1   
8            5                5               4          30  ...        1   
9            5                3               2          37  ...        1   

   num_bat  num_out_wds  cat_fuel_heat  cat_cool  cat_fuel_cook  num_hus_mems  \
0        2           12              5         3              5             5   
1        2           20              5         3              4             3   
2        1           15              5         3              4             4   
3        3           18              5         3              5             5   
4        1           10              5         3              4             2   
5        1            8              5         3              4             4   
6        2            6              5         3              4             3   
7        2            8              5         3              5             4   
8        1           10              5         3              5             4   
9        2            5              5         3              4             5   

   cat_mhh_age  cat_mhh_occu  cat_hh_ann_incm  
0            3             1                6  
1            4             3                7  
2            3             1                3  
3            4             1                6  
4            4             1                5  
5            4             3                5  
6            1             3                5  
7            4             1                6  
8            4             1                7  
9            4             3                2  

[10 rows x 21 columns]

In [7]:
# Check data types for dataframe.
df_raw_hh.dtypes

id_hs              object
id_hh              object
cat_loc_div         int64
cat_sz_cty          int64
cat_hus_typ         int64
num_flr             int64
num_out_wls         int64
cat_hus_dir_fce     int64
cat_hus_blt_yr      int64
num_hus_ar          int64
num_bed             int64
num_liv             int64
num_bat             int64
num_out_wds         int64
cat_fuel_heat       int64
cat_cool            int64
cat_fuel_cook       int64
num_hus_mems        int64
cat_mhh_age         int64
cat_mhh_occu        int64
cat_hh_ann_incm     int64
dtype: object

In [8]:
# Check any NAs.
df_raw_hh.isna().sum()

id_hs              0
id_hh              0
cat_loc_div        0
cat_sz_cty         0
cat_hus_typ        0
num_flr            0
num_out_wls        0
cat_hus_dir_fce    0
cat_hus_blt_yr     0
num_hus_ar         0
num_bed            0
num_liv            0
num_bat            0
num_out_wds        0
cat_fuel_heat      0
cat_cool           0
cat_fuel_cook      0
num_hus_mems       0
cat_mhh_age        0
cat_mhh_occu       0
cat_hh_ann_incm    0
dtype: int64

In [9]:
# Check any negative values for not valid responses.
df_raw_hh.iloc[:,2:].lt(0).sum()

cat_loc_div         0
cat_sz_cty          0
cat_hus_typ         0
num_flr             0
num_out_wls         2
cat_hus_dir_fce     0
cat_hus_blt_yr      0
num_hus_ar          0
num_bed             0
num_liv             0
num_bat             0
num_out_wds         0
cat_fuel_heat       0
cat_cool            0
cat_fuel_cook       0
num_hus_mems        0
cat_mhh_age         0
cat_mhh_occu       65
cat_hh_ann_incm     0
dtype: int64

In [10]:
# Delete data for negative inputs (not valida data..)
df_raw_hh = df_raw_hh[df_raw_hh.num_out_wls > 0]
df_raw_hh = df_raw_hh[df_raw_hh.cat_mhh_occu > 0]
df_raw_hh.iloc[:,2:].lt(0).sum()

cat_loc_div        0
cat_sz_cty         0
cat_hus_typ        0
num_flr            0
num_out_wls        0
cat_hus_dir_fce    0
cat_hus_blt_yr     0
num_hus_ar         0
num_bed            0
num_liv            0
num_bat            0
num_out_wds        0
cat_fuel_heat      0
cat_cool           0
cat_fuel_cook      0
num_hus_mems       0
cat_mhh_age        0
cat_mhh_occu       0
cat_hh_ann_incm    0
dtype: int64

In [11]:
# Check uniqueness of household_id and house_id.
df_raw_hh_ids = df_raw_hh[["id_hh", "id_hs"]]
print(df_raw_hh_ids.duplicated(subset= "id_hh").sum())
print(df_raw_hh_ids.duplicated(subset= "id_hs").sum())

0
0


In [12]:
# Check location distribution.
fig_tmp = px.histogram(df_raw_hh, x= "cat_loc_div", title= "cat_loc_div")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [13]:
# Function to reduce categories for cat_loc_div.
def reduce_cat_loc_div(x):
    
    # List of codes for lumped groups
    lst_tmp_high_lat = [11, 23, 31, 32]
    lst_tmp_mid_lat = [25, 29, 33, 34, 37]
    lst_tmp_low_lat = [21, 22, 24, 26, 35, 36, 38, 39]
    
    # Conditional output
    if x in lst_tmp_high_lat:
        return 1
    elif x in lst_tmp_mid_lat:
        return 2
    elif x in lst_tmp_low_lat:
        return 3
    else:
        return -10

In [14]:
# Create new colums for reduced cat_loc_div and check.
df_raw_hh["cat_loc_div_cor"] = df_raw_hh["cat_loc_div"].apply(reduce_cat_loc_div)
df_raw_hh[["cat_loc_div","cat_loc_div_cor"]].groupby("cat_loc_div").agg(
    {
        "cat_loc_div_cor" : ["min", "max", "mean"],
    }
)

cat_loc_div_cor         
                        min max mean
cat_loc_div                         
11                        1   1  1.0
21                        3   3  3.0
22                        3   3  3.0
23                        1   1  1.0
24                        3   3  3.0
25                        2   2  2.0
26                        3   3  3.0
31                        1   1  1.0
32                        1   1  1.0
33                        2   2  2.0
34                        2   2  2.0
35                        3   3  3.0
36                        3   3  3.0
37                        2   2  2.0
38                        3   3  3.0
39                        3   3  3.0

In [15]:
# Replace old cat_loc_div with new one cat_loc_div_cor and delete cat_loc_div_cor.
df_raw_hh["cat_loc_div"] = df_raw_hh["cat_loc_div"].apply(reduce_cat_loc_div)
df_raw_hh.drop(columns= ["cat_loc_div_cor"], inplace= True)
df_raw_hh["cat_loc_div"].unique()

array([1, 3, 2], dtype=int64)

In [16]:
# Check location distribution.
fig_tmp = px.histogram(df_raw_hh, x= "cat_loc_div", title= "cat_loc_div")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [17]:
# Function to reduce cat_sz_cty.
def reduce_cat_sz_cty(x):
    
    lst_tmp_metro = [1,2]
    
    if x in lst_tmp_metro:
        return 1
    elif x == 3:
        return 2
    else:
        return 2

In [18]:
# Create new colums for reduced cat_sz_cty and check.
df_raw_hh["cat_sz_cty_cor"] = df_raw_hh["cat_sz_cty"].apply(reduce_cat_sz_cty)
df_raw_hh[["cat_sz_cty","cat_sz_cty_cor"]].groupby("cat_sz_cty").agg(
    {
        "cat_sz_cty_cor" : ["min", "max", "mean"],
    }
)

cat_sz_cty_cor         
                      min max mean
cat_sz_cty                        
1                       1   1  1.0
2                       1   1  1.0
3                       2   2  2.0

In [19]:
# Replace old cat_sz_cty with new one cat_sz_cty_cor and delete cat_sz_cty_cor.
df_raw_hh["cat_sz_cty"] = df_raw_hh["cat_sz_cty"].apply(reduce_cat_sz_cty)
df_raw_hh.drop(columns= ["cat_sz_cty_cor"], inplace= True)
df_raw_hh["cat_sz_cty"].unique()

array([1, 2], dtype=int64)

In [20]:
# Check type of house cat_hus_typ uniquness.
df_raw_hh["cat_hus_typ"].unique()

array([3, 2, 1], dtype=int64)

In [21]:
# Filter out not valid inputs from data.
df_raw_hh = df_raw_hh[df_raw_hh.num_flr < 100]

# Check floor number distribution.
fig_tmp = px.histogram(df_raw_hh, x= "num_flr", title= "num_flr")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [22]:
# Delete Extreams of num_flr
df_raw_hh = df_raw_hh[df_raw_hh.num_flr > 0]

# Check floor number distribution.
fig_tmp = px.histogram(df_raw_hh, x= "num_flr", title= "num_flr")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [23]:
# Check outer walls number distribution.
fig_tmp = px.histogram(df_raw_hh, x= "num_out_wls", title= "num_out_wls")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [24]:
# Delete Extreams of num_out_wls
df_raw_hh = df_raw_hh[df_raw_hh.num_out_wls > 1]

# Check outer walls number distribution.
fig_tmp = px.histogram(df_raw_hh, x= "num_out_wls", title= "num_out_wls")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [25]:
# Check distribution of cat_hus_dir_fce.
fig_tmp = px.histogram(df_raw_hh, x= "cat_hus_dir_fce", title= "cat_hus_dir_fce")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [26]:
# Fuction to reduce categories and reorder number with frequency.

def reduce_cat_hus_dir_fce(x):
    if x == 3:
        return 1
    elif (
            x == 5 or 
            x == 6
        ):
        return 2
    elif (
            x == 1 or
            x == 2
        ):
        return 3
    elif (
            x == 4 or
            x == 7 or
            x == 8
        ):
        return 4
    else:
        return 4

In [27]:
# Create new colums for reduced cat_hus_dir_fce and check.
df_raw_hh["cat_hus_dir_fce_cor"] = df_raw_hh["cat_hus_dir_fce"].apply(reduce_cat_hus_dir_fce)
df_raw_hh[["cat_hus_dir_fce","cat_hus_dir_fce_cor"]].groupby("cat_hus_dir_fce").agg(
    {
        "cat_hus_dir_fce_cor" : ["min", "max", "mean"],
    }
)

cat_hus_dir_fce_cor         
                                min max mean
cat_hus_dir_fce                             
1                                 3   3  3.0
2                                 3   3  3.0
3                                 1   1  1.0
4                                 4   4  4.0
5                                 2   2  2.0
6                                 2   2  2.0
7                                 4   4  4.0
8                                 4   4  4.0

In [28]:
# Replace old cat_hus_dir_fce with new one cat_hus_dir_fce_cor and delete cat_hus_dir_fce_cor.
df_raw_hh["cat_hus_dir_fce"] = df_raw_hh["cat_hus_dir_fce"].apply(reduce_cat_hus_dir_fce)
df_raw_hh.drop(columns= ["cat_hus_dir_fce_cor"], inplace= True)
df_raw_hh["cat_hus_dir_fce"].unique()

array([1, 3, 2, 4], dtype=int64)

In [29]:
# Check distribution of cat_hus_dir_fce.
fig_tmp = px.histogram(df_raw_hh, x= "cat_hus_dir_fce", title= "cat_hus_dir_fce")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [30]:
# Check distribution of cat_hus_blt_yr.
fig_tmp = px.histogram(df_raw_hh, x= "cat_hus_blt_yr", title= "cat_hus_blt_yr")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [31]:
# Rename column for merging.
df_raw_hh.rename(columns={"cat_hus_blt_yr":"num_hus_blt_yr"}, inplace= True)

In [32]:
# Convert units of num_hus_ar.
df_raw_hh["num_hus_ar"] = df_raw_hh["num_hus_ar"] * 3.3

# Check distribution of num_hus_ar.
fig_tmp = px.histogram(df_raw_hh, x= "num_hus_ar", title= "num_hus_ar")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [33]:
# Check distribution of num_hus_ar.
fig_tmp = px.histogram(df_raw_hh, x= "num_bed", title= "num_bed")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [34]:
# Delete extreams for num_bed
df_raw_hh = df_raw_hh[df_raw_hh.num_bed <6]

# Check distribution of num_hus_ar.
fig_tmp = px.histogram(df_raw_hh, x= "num_bed", title= "num_bed")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [35]:
# Check distribution of num_liv.
fig_tmp = px.histogram(df_raw_hh, x= "num_liv", title= "num_liv")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [36]:
# Delete Extreams num_liv
df_raw_hh = df_raw_hh[df_raw_hh.num_liv <2]

# Check distribution of num_liv.
fig_tmp = px.histogram(df_raw_hh, x= "num_liv", title= "num_liv")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [37]:
# Check distribution of num_bat.
fig_tmp = px.histogram(df_raw_hh, x= "num_bat", title= "num_bat")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

# Seems we need to deal with some extreams.

In [38]:
# Delete extreams for num_bat. 
df_raw_hh = df_raw_hh[df_raw_hh.num_bat < 3]
fig_tmp = px.histogram(df_raw_hh, x= "num_bat", title= "num_bat")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [39]:
# Check distribution of num_out_wds.
fig_tmp = px.histogram(df_raw_hh, x= "num_out_wds", title= "num_out_wds")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [40]:
# Check distribution of cat_fuel_heat.
fig_tmp = px.histogram(df_raw_hh, x= "cat_fuel_heat", title= "cat_fuel_heat")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [41]:
# Function to lump down cat_fuel_heat and reorder with frquency.
def reduce_cat_fuel_heat(x):
    if (
            x == 4 or
            x == 5
        ):
        return 1
    elif (
            x == 2 or 
            x == 3
        ):
        return 2
    elif (x == 6):
        return 3
    elif (            
            x == 7 or
            x == 8
        ):
        return 4
    else:
        return 5

In [42]:
# Create new colums for reduced cat_fuel_heat and check.
df_raw_hh["cat_fuel_heat_cor"] = df_raw_hh["cat_fuel_heat"].apply(reduce_cat_fuel_heat)
df_raw_hh[["cat_fuel_heat","cat_fuel_heat_cor"]].groupby("cat_fuel_heat").agg(
    {
        "cat_fuel_heat_cor" : ["min", "max", "mean"],
    }
)

cat_fuel_heat_cor         
                            min max mean
cat_fuel_heat                           
1                             5   5  5.0
2                             2   2  2.0
4                             1   1  1.0
5                             1   1  1.0
6                             3   3  3.0
7                             4   4  4.0
8                             4   4  4.0
9                             5   5  5.0

In [43]:
# Replace old cat_fuel_heat with new one cat_fuel_heat_cor and delete cat_fuel_heat_cor.
df_raw_hh["cat_fuel_heat"] = df_raw_hh["cat_fuel_heat"].apply(reduce_cat_fuel_heat)
df_raw_hh.drop(columns= ["cat_fuel_heat_cor"], inplace= True)
df_raw_hh["cat_fuel_heat"].unique()

array([1, 3, 2, 5, 4], dtype=int64)

In [44]:
# Check distribution of cat_fuel_heat.
fig_tmp = px.histogram(df_raw_hh, x= "cat_fuel_heat", title= "cat_fuel_heat")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [45]:
# Check distribution of cat_cool.
fig_tmp = px.histogram(df_raw_hh, x= "cat_cool", title= "cat_cool")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

# Seems we need to deal with extreams.

In [46]:
# Delete extreams for cat_cool. 
df_raw_hh = df_raw_hh[df_raw_hh.cat_cool < 4]
fig_tmp = px.histogram(df_raw_hh, x= "cat_cool", title= "cat_cool")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [47]:
# Check distribution of cat_fuel_cook.
fig_tmp = px.histogram(df_raw_hh, x= "cat_fuel_cook", title= "cat_fuel_cook")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

# Seems we need to deal with extreams.

In [48]:
# Delete extreams for cat_fuel_cook. 
df_raw_hh = df_raw_hh[df_raw_hh.cat_fuel_cook > 2]
fig_tmp = px.histogram(df_raw_hh, x= "cat_fuel_cook", title= "cat_fuel_cook")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [49]:
# Check distribution of cat_sol_pv.
"cat_sol_pv" in list(df_raw_hh.columns)

False

In [50]:
# Check distribution of num_hus_mems.
fig_tmp = px.histogram(df_raw_hh, x= "num_hus_mems", title= "num_hus_mems")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [51]:
# Delete extreams for num_hus_mems. 
df_raw_hh = df_raw_hh[df_raw_hh.num_hus_mems < 7]
fig_tmp = px.histogram(df_raw_hh, x= "num_hus_mems", title= "num_hus_mems")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [52]:
# Function to lump down cat_mhh_age and reorder with frquency.
# def reduce_cat_mhh_age(x):
#     if x in [1,2,3,4]:
#         return 2   
#     else:
#         return 3
    
# Function to convert into numeric data.
def convert_num_cat_mhh_age (x):
    if x == 1:
        return 25
    elif x == 2:
        return 35
    elif x == 3:
        return 45
    elif x == 4:
        return 55
    elif x == 5:
        return 67    
    else:
        return -10

In [53]:
# Create new colums for reduced cat_fuel_heat and check.
df_raw_hh["num_mhh_age"] = df_raw_hh["cat_mhh_age"].apply(convert_num_cat_mhh_age)
df_raw_hh[["cat_mhh_age","num_mhh_age"]].groupby("cat_mhh_age").agg(
    {
        "num_mhh_age" : ["min", "max", "mean"],
    }
)

num_mhh_age          
                    min max  mean
cat_mhh_age                      
1                    25  25  25.0
2                    35  35  35.0
3                    45  45  45.0
4                    55  55  55.0
5                    67  67  67.0

In [54]:
# Delete categorical variable.
df_raw_hh.drop(columns= ["cat_mhh_age"], inplace= True)
df_raw_hh["num_mhh_age"].unique()

array([45, 55, 25, 67, 35], dtype=int64)

In [55]:
# Check distribution of num_mhh_age.
fig_tmp = px.histogram(df_raw_hh, x= "num_mhh_age", title= "num_mhh_age")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [56]:
# Check distribution of cat_mhh_occu.
fig_tmp = px.histogram(df_raw_hh, x= "cat_mhh_occu", title= "cat_mhh_occu")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [57]:
# Check distribution of cat_hh_ann_incm.
fig_tmp = px.histogram(df_raw_hh, x= "cat_hh_ann_incm", title= "cat_hh_ann_incm")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [58]:
# Function to lumpdown annual income range... high area 7,8,9
# def reduce_cat_hh_ann_incm(x):
#     if x in [7,8,9]:
#         return 7
#     else:
#         return x

# Function to convert into numeric variable.
def convert_num_cat_hh_ann_incm (x):
    if x == 1:
        return 12000000
    elif x == 2:
        return 18000000
    elif x == 3:
        return 25000000
    elif x == 4:
        return 42000000
    elif x == 5:
        return 54000000
    elif x == 6:
        return 66000000
    elif x == 7:
        return 78000000
    elif x == 8:
        return 90000000
    elif x == 9:
        return 96000000
    else:
        return -10

In [59]:
# Create new colums for reduced cat_hh_ann_incm and check.
df_raw_hh["num_hh_ann_incm"] = df_raw_hh["cat_hh_ann_incm"].apply(convert_num_cat_hh_ann_incm)
df_raw_hh[["cat_hh_ann_incm","num_hh_ann_incm"]].groupby("cat_hh_ann_incm").agg(
    {
        "num_hh_ann_incm" : ["min", "max", "mean"],
    }
)

num_hh_ann_incm                      
                            min       max        mean
cat_hh_ann_incm                                      
1                      12000000  12000000  12000000.0
2                      18000000  18000000  18000000.0
3                      25000000  25000000  25000000.0
4                      42000000  42000000  42000000.0
5                      54000000  54000000  54000000.0
6                      66000000  66000000  66000000.0
7                      78000000  78000000  78000000.0
8                      90000000  90000000  90000000.0
9                      96000000  96000000  96000000.0

In [60]:
# Delete categorical variable for household annual income.
df_raw_hh.drop(columns= ["cat_hh_ann_incm"], inplace= True)
df_raw_hh["num_hh_ann_incm"].unique()

array([66000000, 78000000, 25000000, 54000000, 18000000, 12000000,
       42000000, 96000000, 90000000], dtype=int64)

In [61]:
# Check distribution of num_hh_ann_incm.
fig_tmp = px.histogram(df_raw_hh, x= "num_hh_ann_incm", title= "num_hh_ann_incm")
fig_tmp.update_layout(width= 750, height= 400)
fig_tmp.show()

In [62]:
# Import final energy consumption data.
df_raw_hh_energy = pd.read_excel(str_raw_data_path, sheet_name= "energy")
df_raw_hh_energy.head(10)

id_hs       id_hh  num_tot_energy_heat  num_tot_gas_heat
0  HS1101000001  HH13110253          8307.760000       6049.400000
1  HS1101000002  HH14110053         24438.403026      21490.566406
2  HS1101000004  HH14110055         12559.750000      10711.610000
3  HS1101000005  HH13110254          8367.795494       5789.515494
4  HS1101000007  HH14110057         13374.450000      10085.810000
5  HS1101000008  HH14110058         11364.270000       7686.910000
6  HS1101000009  HH17110001          6287.812032       1678.212032
7  HS1101000010  HH14110056         13485.940000      10137.960000
8  HS1102000001  HH13110255         15702.059276      12859.759276
9  HS1102000003  HH11110023          9096.680000       7301.000000

In [63]:
# Check energy consumption data type.
df_raw_hh_energy.dtypes

id_hs                   object
id_hh                   object
num_tot_energy_heat    float64
num_tot_gas_heat       float64
dtype: object

In [64]:
# Check NA data of energy data frame.
df_raw_hh_energy.isna().sum()

id_hs                  0
id_hh                  0
num_tot_energy_heat    0
num_tot_gas_heat       0
dtype: int64

In [65]:
# Check negative value in energy data frame.
df_raw_hh_energy.iloc[:,2].lt(0).sum()

0

In [66]:
# Check uniqueness of household_id and house_id.
df_raw_hh_energy_ids = df_raw_hh_energy[["id_hh", "id_hs"]]
print(df_raw_hh_energy_ids.duplicated(subset= "id_hh").sum())
print(df_raw_hh_energy_ids.duplicated(subset= "id_hs").sum())

0
0


In [67]:
# Drop one ids column to preven merging error.
df_raw_hh_energy.drop(columns= ["id_hs"], inplace= True)

In [68]:
df_raw_hh_energy

id_hh  num_tot_energy_heat  num_tot_gas_heat
0     HH13110253          8307.760000       6049.400000
1     HH14110053         24438.403026      21490.566406
2     HH14110055         12559.750000      10711.610000
3     HH13110254          8367.795494       5789.515494
4     HH14110057         13374.450000      10085.810000
...          ...                  ...               ...
2515  HH17390020         23081.730000          0.000000
2516  HH17390021         18057.780000          0.000000
2517  HH17390022          8599.050000          0.000000
2518  HH17390023          3885.170000          0.000000
2519  HH17390024         19246.700000          0.000000

[2520 rows x 3 columns]

In [69]:
# Join two dataframes
df_merged_hh_energy = pd.merge(df_raw_hh, df_raw_hh_energy, how= "inner", on= "id_hh")
df_merged_hh_energy.head(10)

id_hs       id_hh  cat_loc_div  cat_sz_cty  cat_hus_typ  num_flr  \
0  HS1101000001  HH13110253            1           1            3        9   
1  HS1101000002  HH14110053            1           1            2        2   
2  HS1101000004  HH14110055            1           1            2        1   
3  HS1101000007  HH14110057            1           1            1        1   
4  HS1101000008  HH14110058            1           1            1        2   
5  HS1101000009  HH17110001            1           1            1        1   
6  HS1101000010  HH14110056            1           1            1        1   
7  HS1102000001  HH13110255            1           1            2        2   
8  HS1102000003  HH11110023            1           1            1        1   
9  HS1102000004  HH13110257            1           1            1        1   

   num_out_wls  cat_hus_dir_fce  num_hus_blt_yr  num_hus_ar  ...  num_out_wds  \
0            4                1               5       125.4  ...           12   
1            4                3               5        99.0  ...           20   
2            6                3               3       158.4  ...           15   
3            5                2               3        62.7  ...           10   
4            5                1               3       115.5  ...            8   
5            4                2               6       132.0  ...            6   
6            6                1               6       148.5  ...            8   
7            5                2               4        99.0  ...           10   
8            5                1               2       122.1  ...            5   
9            6                1               2       102.3  ...            7   

   cat_fuel_heat  cat_cool  cat_fuel_cook  num_hus_mems  cat_mhh_occu  \
0              1         3              5             5             1   
1              1         3              4             3             3   
2              1         3              4             4             1   
3              1         3              4             2             1   
4              1         3              4             4             3   
5              1         3              4             3             3   
6              1         3              5             4             1   
7              1         3              5             4             1   
8              1         3              4             5             3   
9              1         3              5             2             5   

   num_mhh_age  num_hh_ann_incm  num_tot_energy_heat  num_tot_gas_heat  
0           45         66000000          8307.760000       6049.400000  
1           55         78000000         24438.403026      21490.566406  
2           45         25000000         12559.750000      10711.610000  
3           55         54000000         13374.450000      10085.810000  
4           55         54000000         11364.270000       7686.910000  
5           25         54000000          6287.812032       1678.212032  
6           55         66000000         13485.940000      10137.960000  
7           55         78000000         15702.059276      12859.759276  
8           55         18000000          9096.680000       7301.000000  
9           67         12000000         15988.136785      14001.536785  

[10 rows x 23 columns]

In [70]:
# Check again for any NA values.
df_merged_hh_energy.isna().sum()

id_hs                  0
id_hh                  0
cat_loc_div            0
cat_sz_cty             0
cat_hus_typ            0
num_flr                0
num_out_wls            0
cat_hus_dir_fce        0
num_hus_blt_yr         0
num_hus_ar             0
num_bed                0
num_liv                0
num_bat                0
num_out_wds            0
cat_fuel_heat          0
cat_cool               0
cat_fuel_cook          0
num_hus_mems           0
cat_mhh_occu           0
num_mhh_age            0
num_hh_ann_incm        0
num_tot_energy_heat    0
num_tot_gas_heat       0
dtype: int64

In [71]:
# Check again data types for all variables.
df_merged_hh_energy.dtypes

id_hs                   object
id_hh                   object
cat_loc_div              int64
cat_sz_cty               int64
cat_hus_typ              int64
num_flr                  int64
num_out_wls              int64
cat_hus_dir_fce          int64
num_hus_blt_yr           int64
num_hus_ar             float64
num_bed                  int64
num_liv                  int64
num_bat                  int64
num_out_wds              int64
cat_fuel_heat            int64
cat_cool                 int64
cat_fuel_cook            int64
num_hus_mems             int64
cat_mhh_occu             int64
num_mhh_age              int64
num_hh_ann_incm          int64
num_tot_energy_heat    float64
num_tot_gas_heat       float64
dtype: object

In [72]:
# Save processed dataframe.
df_merged_hh_energy.to_csv("./data/postProcessedData/sKor_data_2017_processed.csv")